### ISSUE TITLE
Use guide stats mica table for guide star histories

### ISSUE THREAD

**Issue by jeanconn** [sot/starcheck#230]

**Comment by taldcroft** [comment]
I presume this would also allow the FOT pre-review to show history correctly?

Would this apply to acq stats as well?

**Comment by jeanconn** [comment]
I still don't have a plan for sync'ing acq and guide stats to GRETA.  In the interim, I'm not sure if on GRETA we will be better served using relatively-recent rdb files, or manually sync'd database.

**Comment by jeanconn** [comment]
Acq stats has had its own PR #187 for a bit.

**Comment by taldcroft** [comment]
About the plan for sync'ing, are you concerned about any technical issues or just getting it done?

It seems like one can follow the simple model for pushing and pulling files done in `kadi` e.g.
https://github.com/sot/kadi/blob/2b1162725c22985d15dfea82f84d15400df6130f/kadi/update_events.py#L216

The main HDF5 files for guide and acq stats are just ~100 Mb, so no problem in doing a daily sync.

Where there is time we will work toward the more generalized syncing service going instead of doing it application-by-application, but alas ...

**Comment by jeanconn** [comment]
Gotcha.  Yeah, I was under the impression that you didn't want me to do the syncing on an application-by-application basis, because it was somewhat the "wrong thing" compared to the generalized syncing.  I think it is no problem to do the sync'ing.  I also hadn't tried to figure out if there were really any issues running sync jobs on this side as me instead of you.  Pathfinder.

**Comment by taldcroft** [comment]
The whole syncing thing is now being done, so that is no longer a blocker.

**Comment by jeanconn** [comment]
Right, the only issue is defining what we actually want to check.

**Comment by jeanconn** [comment]
This was completed.
