### ISSUE TITLE
Downgrade bad pixel warning from red to orange in some cases

### ISSUE THREAD

**Issue by taldcroft** [sot/starcheck#247]
Consider demoting Nearby ACA bad pixel warnings from Red to Orange for cases that are currently Red but have max(Y,Z sep) > dither + 20 + 10 (arcsec).  That keeps the pixel out of the readout window with two pixels of margin.  

Definitely with 2 pixels of margin I would rarely call for a star catalog edit.  Exactly one pixel is a little tight and could result in a hot pixel getting into the background pixels for a credible attitude disturbance.

**Comment by jeanconn** [comment]
Not sure how this would apply.  Right now there is no warning unless min(Y,Z sep) < (dither + 25),  right?  So there are no cases that would be red but greater than dither + 30.  Unless I'm misunderstanding either the current code or your suggestion.

The problem I've seen is just the "all ERs are reviewed as if they have 20 arcsec dither" issue that I started to fix in #215 . Though that still doesn't fix them all, as if there is no dither commanding, we still assume 20 arcsec amplitude due to no amplitude continuity.

**Comment by taldcroft** [comment]
Argh, right.  I keep forgetting the 20 arcsec problem.  I just note that most of the critical warns in JUL0218 would go away in my rule, assuming the correct 8 arcsec dither.  (and I edited min to be  max).

So I see we are already doing the 1-pixel margin for OR's so with #215 this issue will mostly be closed.

**Comment by jeanconn** [comment]
Well, ORs that happen after some dither commanding in the loads...

**Comment by taldcroft** [comment]
If we got kadi commanded states certified for flight would that do the trick for continuity?

**Comment by jeanconn** [comment]
Yes. Also https://github.com/sot/starcheck/pull/215#discussion_r174777134  , but I had missed that I was assigned actions in your reply :smile:

**Comment by jeanconn** [comment]
OBE
