### ISSUE TITLE
Run correctly in root or env conda environment

### ISSUE THREAD

**Issue by jeanconn** [sot/starcheck#312]
Run correctly in root or env conda environment.  See 

https://github.com/sot/starcheck/pull/302#issuecomment-500652993

and following comments.  This may end up being a skare3 issue, but I'm going to track it here for now.

**Comment by taldcroft** [comment]
AFAIK (and this could easily be wrong), starcheck is the only Ska3 app that needs a SKA_ROOT.  Some ideas to discuss:
1. Define SKA_ROOT on-the-fly in `starcheck/src/starcheck` as below.  Not clear if this is robust or if there is a more elegant way.
```
PYTHON_EXE=`which python`
SKA_BIN=`dirname $PYTHON_EXE`
SKA_ROOT=`dirname $SKA_BIN`
```
2. Define `$CONDA_PREFIX` in `ska_envs.*` so that this guaranteed to be defined in both "production" and "standalone env" environments.  I'm less keen on this.
3. Is there some post-activate conda hook we can use to define `SKA_ROOT`?

If (1) works and there are no other applications that need `SKA_ROOT` then I'd vote for that.

**Comment by jeanconn** [comment]
I think this is done.
